config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]


    get 'homes/top'
  end
  # adminsフォルダのhomes#topをルートに指定し、URLを/adminに変更
  namespace :admins do
    root 'homes#top'
  end

  devise_for :admins, controllers: {
    sessions:       'admins/sessions',
    passwords:      'admins/passwords',
    registrations:  'admins/registrations'
  }


  root to: 'homes#top'
  get '/about' => 'homes#about'

  scope module: :public do
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get :check
        patch :withdraw
      end
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]

      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :update, :destroy, :create] do
        collection do
          delete :all_destroy
        end
      end

      resources :orders, only: [:index, :show, :new, :create] do
        collection do
          post :confirm
          get :thanks
        end
      end
    end
  end

  devise_for :customers, controllers: {
    sessions:       'customers/sessions',
    passwords:      'customers/passwords',
    registrations:  'customers/registrations'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, length: {is: 7}, numericality: {only_integer: true}
  validates :address, presence: true
  validates :telephone_number, length: {in: 10..11}, numericality: {only_integer: true}
  
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).order("id ASC")
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報が更新されました"
       redirect_to admins_customer_path(@customer.id)
    else
      render 'edit'
    end

  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController

  before_action :reject_customer, only: [:create]

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
      if @customer
        if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
          flash[:alert] = "このアカウントは退会済みです。"
          redirect_to new_customer_session_path
        end
      else
      end
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/views/admins/customers/edit.html.erb
<div class="container mb-5">
  <h4 class="row mb-5">
    <%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集
  </h4>

  <%= form_with model: @customer, url: admins_customer_path, local: true do |f| %>
    <div class="form-group">
      <%= f.label :id, '会員ID', class: "col-2" %>
      <%= f.label :"#{@customer.id}", class: "form-control-sm col-2" %>
    </div>
    <div class="form-group">
      <%= f.label :"氏名", class: "col-2" %>
      <span><%= f.text_field :last_name, class: "form-control-sm col-2" %></span>
      <span class="ml-2"><%= f.text_field :first_name, class: "form-control-sm col-2" %></span>
    </div>
    <div class="form-group">
      <%= f.label :"フリガナ", class: "col-2" %>
      <span><%= f.text_field :last_name_kana, class: "form-control-sm col-2" %></span>
      <span class="ml-2"><%= f.text_field :first_name_kana, class: "form-control-sm col-2" %></span>
    </div>
    <div class="form-group">
      <%= f.label :postal_code, '郵便番号', class: "col-2" %>
      <%= f.text_field :postal_code, class: "form-control-sm col-2" %>
    </div>
    <div class="form-group">
      <%= f.label :address, '住所', class: "col-2" %>
      <%= f.text_field :address, class: "form-control-sm col-6" %>
    </div>
    <div class="form-group">
      <%= f.label :telephone_number, '電話番号', class: "col-2" %>
      <%= f.text_field :telephone_number, class: "form-control-sm col-2" %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス', class: "col-2" %>
      <%= f.text_field :email, class: "form-control-sm col-2" %>
    </div>
    <div class= "form-group">
      <label class="col-2">会員ステータス</label>
      <%= f.radio_button :is_active, true %>
      <%= f.label :有効 %>

      <%= f.radio_button :is_active, false, class: "ml-2" %>
      <%= f.label :退会 %>
    </div>
    <div class="form-group col">
      <%= f.submit "変更を保存", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admins/customers/index.html.erb
<h4 class="mb-5 ml-3">会員一覧</h4>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
    <tr>
      <td>
        <%= customer.id %>
      </td>
      <td>
        <%= link_to admins_customer_path(customer.id) do %>
        <%= customer.last_name %><%= customer.first_name %>
        <% end %>
      </td>
      <td>
        <%= customer.email %>
      </td>
      <td>
      <% if customer.is_active? %>
        <p>有効</p>
      <% else %>
        <p>退会</p>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination justify-content-center mb-5">
  <%= paginate @customers %>
</div>

app/views/admins/customers/show.html.erb
<div class="container mb-5">
  <div class="row mb-5">
    <h4>
      <%= @customer.last_name %><%= @customer.first_name %>の会員詳細
    </h4>
  </div>

  <div class="row">
      <span class="col-2">会員ID：</span><span class="col-10"><%= @customer.id %></span><br />
      <div class="w-100 mt-3"></div>
      <span class="col-2">氏名：</span><span class="col-10"><%= @customer.last_name %><%= @customer.first_name %></span><br />
      <div class="w-100 mt-3"></div>
      <span class="col-2">フリガナ：</span><span class="col-10"><%= @customer.last_name_kana %><%= @customer.first_name_kana %></span><br />
      <div class="w-100 mt-3"></div>
      <span class="col-2">郵便番号：</span><span class="col-10"><%= @customer.postal_code %></span><br />
      <div class="w-100 mt-3"></div>
      <span class="col-2">住所：</span><span class="col-10"><%= @customer.address %></span><br />
      <div class="w-100 mt-3"></div>
      <span class="col-2">電話番号：</span><span class="col-10"><%= @customer.telephone_number %></span><br />
      <div class="w-100 mt-3"></div>
      <span class="col-2">メールアドレス：</span><span class="col-10"><%=@customer.email %></span><br />
      <div class="w-100 mt-3"></div>
      <span class="col-2">会員ステータス：</span>
        <% if @customer.is_active? %>
        <span class="col-10">有効</span>
        <% else %>
        <span class="col-10">退会</span>
        <% end %>
      <br />
  </div>

  <div class="row">
    <div class="col-2"></div>
    <span class="col-10">
      <%= link_to '編集する', edit_admins_customer_path(@customer.id), class: "btn btn-success mt-3" %>

      <%= link_to '注文履歴一覧を見る', admins_root_path, class: "btn btn-primary ml-5 mt-3" %>
    </span>
  </div>


</div>