config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]


    get 'homes/top'
  end
  # adminsフォルダのhomes#topをルートに指定し、URLを/adminに変更
  namespace :admins do
    root 'homes#top'
  end

  devise_for :admins, controllers: {
    sessions:       'admins/sessions',
    passwords:      'admins/passwords',
    registrations:  'admins/registrations'
  }


  root to: 'homes#top'
  get '/about' => 'homes#about'

  scope module: :public do
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get :check
        patch :withdraw
      end
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]

      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :update, :destroy, :create] do
        collection do
          delete :all_destroy
        end
      end

      resources :orders, only: [:index, :show, :new, :create] do
        collection do
          post :confirm
          get :thanks
        end
      end
    end
  end

  devise_for :customers, controllers: {
    sessions:       'customers/sessions',
    passwords:      'customers/passwords',
    registrations:  'customers/registrations'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def full_address
      '〒' + postal_code + ' ' + address + ' ' + name
    end
    
    validates :name, presence: true
    validates :postal_code, length: {is: 7}, numericality: {only_integer: true}
    validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def total_price(amount, item)
    total = amount.to_i * item.add_tax_price
    return total
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, length: {is: 7}, numericality: {only_integer: true}
  validates :address, presence: true
  validates :telephone_number, length: {in: 10..11}, numericality: {only_integer: true}
  
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  
  has_many :cart_items
  has_many :order_items
  
  belongs_to :genre, optional: true
  
  def add_tax_price
    (self.price * 1.10).round
  end
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :order_items, dependent: :destroy
  
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1}
  
  validates :payment_method, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).order("id ASC")
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報が更新されました"
       redirect_to admins_customer_path(@customer.id)
    else
      render 'edit'
    end

  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end

end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController

  before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page]).reverse_order.per(10)

  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).order("id ASC")
  end

  def show
    @item = Item.find(params[:id])

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
       flash[:notice] = "新しく商品が追加されました"
       redirect_to admins_item_path(@item.id)
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       flash[:notice] = "商品情報が更新されました"
       redirect_to admins_item_path(@item.id)
    else
      render 'edit'
    end

  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController

  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order.shipping_cost = 800
  end

  def update
  end


end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  # sign_in後のリダイレクト先の指定
  def after_sign_in_path_for(resource)
    admins_homes_top_path
  end
  
  # sign_out後のリダイレクト先の指定
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number])
    
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    @items = Item.all
    
  end
  
  def about
  end
  
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/items/edit.html.erb
<div class="container">
  <div class="mb-4">
    <h4>商品編集</h4>
  </div>
      <div>
        <%= form_with model: @item, url: admins_item_path, local: true do |f| %>
          <div class="row form-group">
            <%= f.label :image, '商品画像', class: "col-2" %>
            <%= f.attachment_field :image, class: "col-4" %>
          </div>
          <div class="row form-group">
            <%= f.label :neme, '商品名', class: "col-2" %>
            <%= f.text_field :name, class: "col-4" %>
          </div>
          <div class="row form-group">
            <%= f.label :introduction, '商品説明', class: "col-2" %>
            <%= f.text_area :introduction, class: "col-4" %>
          </div>
          <div class="row form-group">
            <%= f.label :price, '税抜価格', class: "col-2" %>
            <%= f.text_field :price, class: "col-4" %>円
          </div>
          <div class="col offset-2 form-group">
            <%= f.submit "変更を保存", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
</div>

app/views/admins/items/index.html.erb
<h4 class="ml-3">商品一覧</h4>
<div class="text-right mb-3 mr-3">
  <%= link_to '+', new_admins_item_path, class: "btn btn-shadow btn-lg border-dark" %>
</div>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td>
        <%= item.id %>
      </td>
      <td>
        <%= link_to admins_item_path(item.id) do %>
        <%= item.name %>
        <% end %>
      </td>
      <td>
        <%= item.price.to_s(:delimited) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination justify-content-center">
<%= paginate @items %>
</div>

app/views/admins/items/new.html.erb
<div class="container">
  <h4>商品新規登録</h4>

  <div class="row">
    <%= form_with model: @item, url: admins_items_path, local: true do |f| %>
    <div class="col-sm form-group">
      <%= f.label :image, '商品画像',class: "col-form-label" %>
      <%= f.attachment_field :image, class: "form-control-file" %>
    </div>
    <div class="col-sm form-group">
      <%= f.label :name, '商品名' %>
      <%= f.text_field :name, class: "form-control", placeholder: "商品名" %>
    </div>
    <div class="col-sm form-group">
      <%= f.label :introduction, '商品説明' %>
      <%= f.text_area :introduction, class: "form-control", placeholder: "ここに説明文を記述します" %>
    </div>
    <div class="col-sm form-group">
      <%= f.label :price, '税抜き価格' %>
      <%= f.text_field :price, class: "form-control", placeholder: "1000" %>円
    </div>
    <div class="col-sm form-group">
      <%= f.submit "新規登録", class: "btn btn-success" %>
    </div>
      <% end %>
  </div>
</div>

app/views/admins/items/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-sm-2">商品詳細</h4>
  </div>
  <div class="row">
    <%= attachment_image_tag @item, :image, format: 'jpeg', size: "100x180", class: "col-4" %>
    <div class="col-8">
      <p>商品名：<%= @item.name %></p>
      <p>商品説明：<%= @item.introduction %></p>
      <p>税込み価格(税抜価格)：<%= @item.add_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>)円</p>
    <div class="btn justify-content-center">
      <%= link_to '編集する', edit_admins_item_path(@item.id), class: "btn btn-success" %>
    </div>
    </div>
  </div>
</div>

app/views/admins/orders/show.html.erb
<div class="container">
 <h4 class="mx-auto">注文履歴詳細</h4>

 <div class="row gutters">
  <strong class="col-2">購入者</strong>
    <%= link_to "#{@order.customer.last_name}#{@order.customer.first_name}", admins_customer_path(@order.customer) %><br />

  <div class="w-100 mt-2"></div>

  <strong class="col-2">注文日</strong>
    <%= @order.created_at %><br />

  <div class="w-100 mt-2"></div>

  <strong class="col-2">配送先</strong>
    〒<%= @order.postal_code %><%= @order.address %><br />
  <div class="w-100"></div>
    <span class="col offset-2"><%= @order.name %></span><br />

  <div class="w-100 mt-2"></div>

  <strong class="col-2">支払方法</strong>
    <%= @order.payment_method_i18n %><br />
 </div>

  <div class="row">
    <table class="table col-8 mt-3">
      <thead class="table-light">
         <tr>
             <th>商品名</th>
             <th>単価（税込）</th>
             <th>数量</th>
             <th>小計</th>
         </tr>
      </thead>

      <tbody>
         <% @order.order_items.each do |order_item| %>
         <tr>
             <td>
                 <%= order_item.item.name %>
             </td>
             <td>
                 <%= order_item.item.add_tax_price.to_s(:delimited) %>
             </td>
             <td>
                 <%= order_item.amount %>
             </td>
             <td>
                 <%= order_item.item.add_tax_price * order_item.amount %>
             </td>
         </tr>
         <% end %>
      </tbody>
    </table>


    <div class="align-self-end col-3">
      <strong class="col offset-3">商品合計</strong>
         <%= @order.total_payment - @order.shipping_cost %>円<br />

      <strong class="col offset-5">送料</strong>
         <%= @order.shipping_cost %>円<br />

      <strong class="col offset-2">請求金額合計</strong>
         <%= @order.total_payment.to_s(:delimited) %>円
    </div>
  </div>
</div>

app/views/admins/orders/update.html.erb
<h1>Admins::Orders#update</h1>
<p>Find me in app/views/admins/orders/update.html.erb</p>