config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]


    get 'homes/top'
  end
  # adminsフォルダのhomes#topをルートに指定し、URLを/adminに変更
  namespace :admins do
    root 'homes#top'
  end

  devise_for :admins, controllers: {
    sessions:       'admins/sessions',
    passwords:      'admins/passwords',
    registrations:  'admins/registrations'
  }


  root to: 'homes#top'
  get '/about' => 'homes#about'

  scope module: :public do
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get :check
        patch :withdraw
      end
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]

      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :update, :destroy, :create] do
        collection do
          delete :all_destroy
        end
      end

      resources :orders, only: [:index, :show, :new, :create] do
        collection do
          post :confirm
          get :thanks
        end
      end
    end
  end

  devise_for :customers, controllers: {
    sessions:       'customers/sessions',
    passwords:      'customers/passwords',
    registrations:  'customers/registrations'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController

  before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page]).reverse_order.per(10)

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    @items = Item.all
    
  end
  
  def about
  end
  
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container">
  <h1 class="display-3 text-center mb-4">About</h1>

  <div class="text-center font-weight-bold justify-content-center">
    ながのCAKEは全国発送可能なケーキ屋さんです。<br />
    お子様からお年寄りの方までお召し上がりいただけるよう、<br />
    様々なバリエーションをご用意しております。<br />
    また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br />
    ぜひご注文ください。<br />
  </div>
</div>

app/views/homes/top.html.erb
<div class="container mb-4">
  <div class="row mt-5 mb-5">
    <div class="col-5 offset-3 border border-dark text-justify pt-4 pb-4 mb-4">
      ようこそ、ながのCAKEへ！<br />
      このサイトは、ケーキ販売のECサイトになります。<br />
      会員でない方も商品の閲覧はできますが、<br />
      購入には会員登録が必要になります。<br />
    </div>
  </div>

  <div class="row">
    <h4 class="col-2 offset-2">新着商品</h4>
  </div>
  <div class="row">
    <% @items.first(4).each do |item| %>
      <div class="col-sm-3">
        <div class="card">
          <div class="col offset-3">
          <%= attachment_image_tag item, :image, format: 'jpeg', size: "100x100" %>
          </div>
          <div class="card-body text-center">
            <%= link_to customers_item_path(item) do %>
            <strong class="card-title"><%= item.name %></strong>
            <% end %>
            <p class="card-text">¥<%= item.price.to_s(:delimited) %></p>
          </div>
        </div>
      </div>
        <% end %>
  </div>
        <!--link_toで「全ての商品を見る>」のコードを書く-->
        <%= link_to "全ての商品を見る＞", customers_items_path, class: 'col offset-10' %>
</div>