config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]


    get 'homes/top'
  end
  # adminsフォルダのhomes#topをルートに指定し、URLを/adminに変更
  namespace :admins do
    root 'homes#top'
  end

  devise_for :admins, controllers: {
    sessions:       'admins/sessions',
    passwords:      'admins/passwords',
    registrations:  'admins/registrations'
  }


  root to: 'homes#top'
  get '/about' => 'homes#about'

  scope module: :public do
    resource :customers, only: [:show, :edit, :update] do
      collection do
        get :check
        patch :withdraw
      end
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]

      resources :items, only: [:index, :show]
      resources :cart_items, only: [:index, :update, :destroy, :create] do
        collection do
          delete :all_destroy
        end
      end

      resources :orders, only: [:index, :show, :new, :create] do
        collection do
          post :confirm
          get :thanks
        end
      end
    end
  end

  devise_for :customers, controllers: {
    sessions:       'customers/sessions',
    passwords:      'customers/passwords',
    registrations:  'customers/registrations'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def full_address
      '〒' + postal_code + ' ' + address + ' ' + name
    end
    
    validates :name, presence: true
    validates :postal_code, length: {is: 7}, numericality: {only_integer: true}
    validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def total_price(amount, item)
    total = amount.to_i * item.add_tax_price
    return total
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (self.is_active == true)
  end
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, length: {is: 7}, numericality: {only_integer: true}
  validates :address, presence: true
  validates :telephone_number, length: {in: 10..11}, numericality: {only_integer: true}
  
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  
  has_many :cart_items
  has_many :order_items
  
  belongs_to :genre, optional: true
  
  def add_tax_price
    (self.price * 1.10).round
  end
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :order_items, dependent: :destroy
  
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1}
  
  validates :payment_method, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController

  before_action :authenticate_admin!
  def top
    @orders = Order.all.page(params[:page]).reverse_order.per(10)

  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).order("id ASC")
  end

  def show
    @item = Item.find(params[:id])

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
       flash[:notice] = "新しく商品が追加されました"
       redirect_to admins_item_path(@item.id)
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       flash[:notice] = "商品情報が更新されました"
       redirect_to admins_item_path(@item.id)
    else
      render 'edit'
    end

  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController

  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order.shipping_cost = 800
  end

  def update
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number])
    
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    @items = Item.all
    
  end
  
  def about
  end
  
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/_header.html.erb
<header class="border-bottom">
  <nav class="navbar navbar-expand-sm navbar-light mt-2">
    <% if admin_signed_in? %>
    <%= link_to "NaganoCake", admins_homes_top_path, class: "navbar-brand" %>
    <% else %>
    <%= link_to "NaganoCake", root_path, class: "navbar-brand" %>
    <% end %>

    <ul class="navbar-nav ml-auto">
      <% if customer_signed_in? %>
      <li class="nav-item mt-2 mr-4">
        ようこそ、<%= current_customer.last_name %>さん！
      </li>
      <li class="nav-item">
        <%= link_to "マイページ", customers_path, class: 'nav-link text-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to "商品一覧", customers_items_path, class: 'nav-link text-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to "カート", customers_cart_items_path, class: 'nav-link text-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
      </li>

      <% elsif admin_signed_in? %>
      <li class="nav-item">
        <%= link_to "商品一覧", admins_items_path, class: 'nav-link text-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to "会員一覧", admins_customers_path, class: 'nav-link text-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to "注文履歴一覧", admins_homes_top_path, class: 'nav-link text-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
      </li>

      <% else %>
      <li class="nav-item">
        <%= link_to "About", about_path, class: 'nav-link text-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to "商品一覧", customers_items_path, class: 'nav-link text-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
      </li>
      <li nav-item>
        <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
      </li>

      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <!--管理者のログアウトのリンクを出すため、とりあえず、link_toを記述。のちに変更予定-->
    <!--<%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>-->

    <!--<%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>-->

    <div>
      <%= render "layouts/header" %>
    </div>

    <div>
      <p class="flash" id="notice"><%= flash[:notice] %></p>
    </div>

    <main class="mb-auto">
    <%= yield %>
    </main>

    <footer class="border-top text-white pt-5 pb-4">

    </footer>
  </body>
</html>